title: Agro Connections
description: Conexión confiable de talento mexicano con EE.UU.
baseurl: ""  # Deja en blanco si estás usando un dominio personalizado
url: "https://agroconnections.mx"  # Cambia si usas GitHub Pages en formato usuario.github.io

theme: minima  # Puedes cambiar a 'cayman' si prefieres el estilo anterior

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/TU_USUARIO" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/TU_PERFIL" }
    - { platform: whatsapp, user_url: "https://wa.me/524831190497" }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

include:
  - index_ordenado_final.html
  - style_ordenado.css
  - script_ordenado.js
  - logo.png
  - images/

exclude:
  - README.md
  - node_modules
  - .vscode
  - .idea
